# Generated by Django 3.2.13 on 2022-04-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="closed_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="closed date"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=30,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="loanterm",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_term",
                to="loans.loan",
                verbose_name="loan",
            ),
        ),
    ]
