# Generated by Django 3.2.13 on 2022-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20220423_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanterm',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='paid amount'),
            preserve_default=False,
        ),
    ]
