# Generated by Django 3.2.13 on 2022-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanterm_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanterm',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='paid amount'),
        ),
    ]
